version: '3'

services:
  spring-boot:
    build: spring-boot
    ports:
      - '8081:8080'
  micronaut:
    build: micronaut
    ports:
      - '8082:8080'
  quarkus:
    build:
      context: quarkus
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - '8083:8080'
  javalin:
    build: javalin
    ports:
      - '8084:7000'
  tomee:
    build: tomee
    ports:
      - '8085:8080'
  helidon-se:
    build: helidon-se/target
    ports:
      - '8086:8080'

  